# Generated by Django 5.1.3 on 2024-12-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitschy_api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productimage",
            name="img_url",
        ),
        migrations.AddField(
            model_name="productimage",
            name="image",
            field=models.FileField(null=True, upload_to="product_images"),
        ),
    ]
