# Generated by Django 5.1.3 on 2024-11-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitschy_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="membership_id",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
