# Generated by Django 5.1.3 on 2024-12-15 12:12

from django.db import migrations, models

import kitschy_api.models.product_images


class Migration(migrations.Migration):

    dependencies = [
        ("kitschy_api", "0002_remove_productimage_img_url_productimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.FileField(
                null=True,
                upload_to=kitschy_api.models.product_images.ProductImage.get_s3_path,
            ),
        ),
    ]
