# Generated by Django 5.1.3 on 2024-11-12 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitschy_api', '0002_address'),
        ('kitschy_api', '0002_product'),
    ]

    operations = [
    ]
