# Generated by Django 5.1.3 on 2024-11-19 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kitschy_api", "0002_alter_user_membership_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartitem",
            options={"ordering": ["-item_id"]},
        ),
        migrations.RenameField(
            model_name="cartitem",
            old_name="items_id",
            new_name="item_id",
        ),
        migrations.RenameField(
            model_name="orderitems",
            old_name="items_id",
            new_name="item_id",
        ),
    ]
