# Generated by Django 5.1.3 on 2024-11-25 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kitschy_api", "0002_alter_user_phone_number"),
        ("kitschy_api", "0002_product_status_alter_user_phone_number"),
    ]

    operations = []
