# Generated by Django 5.1.3 on 2024-11-20 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kitschy_api", "0003_alter_cartitem_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="address",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="user_id",
            new_name="user",
        ),
    ]
