# Generated by Django 5.1.3 on 2024-11-12 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitschy_api', '0003_merge_0002_address_0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='user',
            new_name='user_id',
        ),
    ]
