# Generated by Django 5.1.3 on 2024-11-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitschy_api", "0003_merge_20241125_1848"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("MERCH", "Merchandise"),
                    ("PRINT", "Misbeeks' Printing"),
                    ("CAFE", "Cafe and Pastries"),
                    ("MINIMART", "Mini-mart"),
                    ("WORKSHOP", "Workshop"),
                ],
                default="MERCH",
            ),
        ),
    ]
