# Generated by Django 5.1.3 on 2024-12-15 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kitschy_api", "0003_alter_productimage_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productimage",
            old_name="image",
            new_name="img_url",
        ),
    ]
