# Generated by Django 5.1.3 on 2024-11-20 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kitschy_api", "0004_rename_user_id_address_user_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitems",
            old_name="order_id",
            new_name="order",
        ),
        migrations.RenameField(
            model_name="orderitems",
            old_name="product_id",
            new_name="product",
        ),
        migrations.RenameField(
            model_name="productimage",
            old_name="product_id",
            new_name="product",
        ),
        migrations.AlterUniqueTogether(
            name="orderitems",
            unique_together={("order", "product")},
        ),
    ]
