# Generated by Django 5.1.3 on 2024-11-12 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitschy_api', '0004_rename_user_address_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-user_id']},
        ),
    ]
