# Generated by Django 5.1.3 on 2024-12-14 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kitschy_api", "0003_merge_20241126_0125"),
        ("kitschy_api", "0005_product_creators"),
    ]

    operations = []
