# Generated by Django 5.1.3 on 2024-11-12 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kitschy_api", "0005_alter_address_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"ordering": ["-address_id"]},
        ),
    ]
