# Generated by Django 5.1.3 on 2024-11-13 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kitschy_api", "0007_order"),
        ("kitschy_api", "0007_productimage"),
    ]

    operations = []
