# Generated by Django 5.1.3 on 2024-11-13 05:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitschy_api", "0009_orderitems"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitems",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterUniqueTogether(
            name="orderitems",
            unique_together={("order_id", "product_id")},
        ),
    ]
