# Generated by Django 5.1.3 on 2024-11-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitschy_api", "0011_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="method",
            field=models.CharField(
                choices=[
                    ("COD", "Cash on Delivery"),
                    ("ONLINE", "Online Payment"),
                ],
                default="COD",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="Pending",
                max_length=50,
            ),
        ),
    ]
